---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:R+jCaDWHhUbvk03L7V1fGjI0Ay9Y,iv:Z7W/ewSBso6mn2GxfVU2cWW1MMonN2L+DVcsgMvGj9I=,tag:6feisOusWGHoEj9PhmcW+w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:dcX3gABRkTw78vhOfp+HF3vq+QKCl7kwnGH/r8B3xDBdgJjNWw==,iv:79xP0DSlLWI7JpeD3fJ1f494xb8kDO6aKakJYu4hAWk=,tag:fW1zuDjWJ/2G4cxm+/20WA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:YoWnTYbeHjw/GQnt6ak=,iv:w9+tjuTnL+tnonwm9t9rDI4Pn9jVgZ8g3A5hciOMrZs=,tag:3RoLqH+TYfvh68MDK9eCCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcjY2OEdLRXRSMTUvRzBv
            aHpzb25PTHFwVEp0WThNaVUzYVYwMjk4U25NClhBSmlRNW5UdHV6Zm54T0lVNk5o
            eEloK1JvanFCYUwxb0lOR09XWVFVT0EKLS0tIDZCNndGSitIaGMxN1JuMDZIV2Zi
            WEptTkVKckF5L0hxNFVPZU1uZFZCeE0K/iSDpzlDhbTlN8QtLboPIJIVUNs1Yg8F
            YfjYNnfH3nCYim428Mhb7sQxTDHrLgGhDUhACNyDdLO8EaiBmlmQFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T05:39:59Z"
    mac: ENC[AES256_GCM,data:JkBBJGFkadOjaOHQ024axrIarru++kzUBL/y3U/Yl+A7v30iHX2UKAfcZXm1HO0/jOdYuoMs1PPOGpBWM4xq4bnaq8NBoRZh1Nd5WkTVzodZE7HjgO5/OkEnkpkIi8Ek2SpMYXtv1SX9AHIt66606qba+HgSg3lR8kzSu5qoUCk=,iv:A/3p/ULuBY1ZGtvpFUOZ0jtN62PWbVhfoiM9qCoR3sI=,tag:vYAnKMB+hh2i0FnD5dEWqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
