---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nzbget-config-v1
  namespace: media
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
