apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  releaseName: nzbget
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbget
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
    # Default values
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/nzbget/values.yaml
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "nzbget"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: nzbget.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - nzbget.${SECRET_DOMAIN}
            secretName: nzbget-tls

    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config-v1

      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.3"
            path: /mnt/Data/media
        mountPath: /media
        readOnly: false

      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.3"
            path: /mnt/Data/media/downloads
        mountPath: /downloads
        readOnly: false

    resources:
      requests:
        memory: 1000Mi
        cpu: 500m
      limits:
        memory: 2000Mi
        cpu: "4"
