apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:nlr7hR9VLKB2E0oA30VZzye5EWnq,iv:2w+EGIyyTZHlzwXvxyZMQDK7aa6dE4fjvCd7i3YT6VM=,tag:R/EEEQ3ZqmjGAj3NQJWxtQ==,type:str]
    api-key: ENC[AES256_GCM,data:nccefKUvF0JNwqo3orX5+yFlof4NTNGpKaBSDXySJzVN1beGsg==,iv:I1Yx5q5C9wQkIEVhezQrrPxkfwMDB04ww+44r6UaAvs=,tag:6eZSDCADSU0d+CrqLPXHfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NjAvTzVWS0pjNXphRkdj
            RWtRbHlnRENEWFJmdnU5K2ExcHRTOGltRURBCnlldjBnQnlmamNYc1hJVXNUVWcy
            NTZOZXNZbGpZVEFTeHRiQTFjSXd1WVkKLS0tIGxpbzNuRUg1VThIenl5RVNqZ0RF
            ZWtjaEVXWXd3d3ZheWJFNVBCSUs4djAKM8bI3fzvV5LF5Y0bcp1rg/Op1YaFlgIw
            oVSY4Em2n7GO3NVjXZ5Ra6LBC5tn2fYcJTAxQLGZ7AqbMveEcGS4WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-07T12:13:25Z"
    mac: ENC[AES256_GCM,data:o7OC0WT+zNNHsBu5mHrtqVl1oyaqw51l3WY09Mgh90G+mB2GOVZRVkKSgWYyJ67ZSesEg8tw2/V0g526rjf2dp8fc1LJ4IEmoJ+VhhSYi7jzao+uzf5ZrwCNhYsEWFeq1aw6idFGf700P70cL4/eumX74ylvzSccCJbcFcK6QZk=,iv:rX0fkPLFq68arkZb/szX6sJ89lYZqPzAbUwUuYczZXQ=,tag:OsQP2u43EoPikIsW3FyvkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
