---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-v1
  namespace: media
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
