---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: k10-disaster-recovery
  namespace: kasten-io
spec:
  locationSpec:
    type: FileStore
    fileStore:
      claimName: k10-backups
      path: k10-disaster-recovery
    credential:
      secretType: ""
      secret:
        apiVersion: ""
        kind: ""
        name: ""
        namespace: ""
  type: Location
