---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k10-backups
spec:
  storageClassName: k10-backup-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.1.0.3"
    path: /mnt/Data/backups/k10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k10-backups
  namespace: kasten-io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: k10-backup-nfs
  resources:
    requests:
      storage: 1Mi
