---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
    # Default values
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/radarr/values.yaml
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.0.5.5981

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "radarr"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: radarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - radarr.${SECRET_DOMAIN}
            secretName: radarr-tls

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1

      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.3"
            path: /mnt/Data/media
        mountPath: /media
        readOnly: false

    resources:
      requests:
        memory: 1000Mi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: "2"
