# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:N9Hn1ky7EtJi,iv:rBZn6hxKt5NlfZzGyOShC7k+TR/X9HN0ZK0Qsbg2VKk=,tag:uaYTSQQtC2M8CH1C2m6RWA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6Q0hvdxBKtcyp99gG6VLeT9nzrfE,iv:udeV9bq/12Zp155yOEPDEp+NSXmtyzcM9PProExMcd4=,tag:1FsN8HYlNnH7Pv6ZhDFGRA==,type:str]
    SECRET_DISCORD_ADDRESS: ENC[AES256_GCM,data:Mj+ptZfz/OVQQuXr0OdF2T2GzDpj3Zvx0k+TMg5nFltr+xdjsXWKbsrFj9Nt+5YpYMUMWhTdXIsIwKv38atm0JN44vRwxwpWXaG1kGmZ60o+sc2/6Kymgrp++7PZSjvcfD62p3NRvUuTEIEbShmZtMYH5PMtQy4f,iv:nuLqOPyciMC9Uvgvw/iJubT8pSPXl0xXwq/4APFp+OY=,tag:yd+LguU4VVV7yYClGWeDOg==,type:str]
    BOTKUBE_TOKEN: ENC[AES256_GCM,data:B1rO6xh5OIHiBXmyHMctH1jNBz+hmZ8qxMJoyGdFVyZJZQWNlgqs80QBPDx9f7bTmLh5InwO6A5qBUw=,iv:ie7Ao/hj6nBhYZSA8bGMpFGBvqOJ9AdZKpKM/qle8wA=,tag:OGstnrCnzkljuYnby9XW0w==,type:str]
    BOTKUBE_BOTID: ENC[AES256_GCM,data:XKRhghFe1qaGDvjqxgEJf0CO,iv:oQ+FJeBzdzzI0gk38d8tNZF+ajaZVMjAn1yCrziJj6o=,tag:za/3yWfw5Gx2dC2FW4RMIQ==,type:str]
    BOTKUBE_CHANNEL: ENC[AES256_GCM,data:rJjof6N7IBR9SLmZgksv0K2Y,iv:yGA8xU/VaNKDBMpvyJrLSoJkujDdXjzqcSYAnXMWE7o=,tag:f3i/TdFRqgyYao6lXj02tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbzF3K1BKSTJIekdFclUw
            ZkMxa1F1ZlA4YnpRS0VHalFQZ2t0ZEU0eVQ4CmswRDlUUGtvOWZUelBlU2JoazBZ
            RFlSN0tMb3h6ckdhc0haZG5wSndaV00KLS0tIGQ2OXNhZmxkTXNvQ3c2TkkxSU45
            L0FKOXJteUtHSmVLSEk0YnZhUEI5R2sKmNvFvUWpeE54KJtVcNEcBziNQ2fXHImM
            I2XXZ9rnUnvnPkhtS+sAeQmHWwi2CzWAyNbAxcmvD0truTmZNZoN/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T03:01:25Z"
    mac: ENC[AES256_GCM,data:lJQkl1KqULQmfftSS5w4+5ha1SBBsMkbAvwcAhWOvQzSfMt1avIRz1L7TeIxGB40GwCq94SW2TwOGSbnlyKkmnWgYinRcIJRl4DotXwH8ryTtYJzaBxi+EXgq0bDoLtCZJMxY+HMa0SWQ4v/q7IHieDt5GBL+K3bxk3vem/oDtc=,iv:endNbsQIYdRYqFMBL5CYWOFfvxqvW3/hXif4jxRsets=,tag:Yl/ZzFod4dAXHveE6/Y4fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
