apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 15.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/k8s-at-home/charts/blob/master/charts/stable/sonarr/values.yaml

    values:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "sonarr"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: sonarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          hosts:
            - sonarr.${SECRET_DOMAIN}
          secretName: sonarr-tls

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1

      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.1.0.3"
            path: /mnt/Data/media
        mountPath: /media
        readOnly: false
