---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-config
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
