---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-config
  namespace: jenkins
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
