---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-config
  namespace: jenkins
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
