---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-config-v1
  namespace: jenkins
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-block
