---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: v8.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    jenkinsUser: "${JENKINS_USER}"
    jenkinsPassword: "${JENKINS_PASSWORD}"

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "code-tags-check"
      hosts:
        - host: "jenkins.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "jenkins.${SECRET_DOMAIN}"
          secretName: "jenkins-tls"
      persistance:
        enabled: true
        storageClass: "managed-nfs-storage"
        accessModes:
          - ReadWriteOnce
        size: 100Mi
