---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: v8.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      - name: jenkinsUser
        valueFrom:
          secretKeyRef:
            name: jenkins-secret
            key: JENKINS_USER
      - name: jenkinsPassword
        valueFrom:
          secretKeyRef:
            name: jenkins-secret
            key: JENKINS_PASSWORD
    envFrom:
      - secretKeyRef:
          name: jenkins-secret

    service:
      type: ClusterIP

    persistance:
      config:
        enabled: true
        existingClaim: jenkins-config
