---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: jenkins
      version: 11.0.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    jenkinsUser: ${JENKINS_USER}
    jenkinsPassword: ${JENKINS_PASSWORD}

    extraEnvVars:
      - name: JENKINS_USER
        value: ${JENKINS_USER}
      - name: JENKINS_PASSWORD
        value: ${JENKINS_PASSWORD}

    service:
      type: ClusterIP

    persistance:
      config:
        enabled: true
        existingClaim: jenkins-config-v1
