apiVersion: v1
kind: Secret
metadata:
    name: jenkins
    namespace: jenkins
type: Opaque
stringData:
    JENKINS_USER: ENC[AES256_GCM,data:4rfdwFeT,iv:pQswdkOZx7ViG3xLW2RL+38RzvSOhaBLQaSSyAJcCFs=,tag:zZb1/0rrXYpMOkk8196iFw==,type:str]
    JENKINS_PASSWORD: ENC[AES256_GCM,data:Aq2PC6Lzx7bmn+k=,iv:KLt+m5V5zzvfDEyxg/TgxB+ytkei3xQHoB7vQodBZxQ=,tag:hGAJVV3iqdzBJSygfo0Sdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QnFUYVhtamFyczhpMHRj
            UXpJSWxmZ09XcGhESHkzMDNMeGxCU01ONUNBCk5wZCtxQkN1TmxJMGFqMWhPQnRh
            aVAxc0RVS3FRWnlneHJVcitLOTdrOXcKLS0tIGpIK0trMmEwcURBMDNoWU5sejZW
            d05uYTNoM2ZYbHJwU0xqaHp4NEpkVmcKF87bgTORE6DNmN2FqWD81aKwP/ccmgaV
            hu1OiYcRh7qgds18iMxidXTRaGihavtgCmJWIXTzh+LIXMPdYTKJcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-07T20:31:16Z"
    mac: ENC[AES256_GCM,data:v2tngEqHy1SVUPuUtu3X/+5NBHEIf+p7TTaNy1QMleplIfGYH+oNGcgLIITw6KNZch6I2Ja66QJCY18We5BWXFkfkTSFl4IuYV7F/IgckFnGvaMNxPgk9zu49sgqfda+K6Qqqdv67XnmsPsEpUFxQgcyLIMma3OTo/LQKKrI/t4=,iv:5XdKX36e53XoJgoWFo4rOQ44fTnaiA58AS3iALb7dxE=,tag:Oz17e+xCLu36/lVTT0SMPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
