apiVersion: v1
kind: Secret
metadata:
    name: jenkins-secret
    namespace: jenkins
stringData:
    JENKINS_USER: ENC[AES256_GCM,data:4rfdwFeT,iv:pQswdkOZx7ViG3xLW2RL+38RzvSOhaBLQaSSyAJcCFs=,tag:zZb1/0rrXYpMOkk8196iFw==,type:str]
    JENKINS_PASSWD: ENC[AES256_GCM,data:kEIEITjoN45miLQ=,iv:/F2AtGkTVdIpVBtG0kf8lga0A1BKaW4pemNyC+TEWCw=,tag:GtJeJQDcEB5BXVdF5QrLxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QnFUYVhtamFyczhpMHRj
            UXpJSWxmZ09XcGhESHkzMDNMeGxCU01ONUNBCk5wZCtxQkN1TmxJMGFqMWhPQnRh
            aVAxc0RVS3FRWnlneHJVcitLOTdrOXcKLS0tIGpIK0trMmEwcURBMDNoWU5sejZW
            d05uYTNoM2ZYbHJwU0xqaHp4NEpkVmcKF87bgTORE6DNmN2FqWD81aKwP/ccmgaV
            hu1OiYcRh7qgds18iMxidXTRaGihavtgCmJWIXTzh+LIXMPdYTKJcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-07T11:53:20Z"
    mac: ENC[AES256_GCM,data:BuuujB8gqEMs9Ecus4uQWlvxUmaWjzKJ41PoNsXAbI9kb5o5zXLNrLgoI+KRtTLBbyzbtJ4qUm8NOAbLkENVcD03Qdx+XvQC8c3Jyy4SqOVj2F/OlwUNuAg/A6sm3P4xa1NFKV4JEIwbOuQDRIg53vPm3/maITgeY+e5a6LlNB4=,iv:g9MccW0eeQCWuhB3TUwo/jv8uuaCFnRoDf114Oeu78k=,tag:Z/rrXnR0tdq0NG3lzWTz0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
