apiVersion: v1
kind: Secret
metadata:
    name: jenkins
    namespace: jenkins
    label:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: jenkins
        meta.helm.sh/release-namespace: jenkins
type: Opaque
stringData:
    jenkins-user: ENC[AES256_GCM,data:BIsdjFRZ,iv:lu1brF7OfR+h/a6dVRP2+7Fwq5jP0i5Kl9Dt/FQNqJw=,tag:l2ZWLG8LMJIdCbo1Jo9GsA==,type:str]
    jenkins-password: ENC[AES256_GCM,data:X4hPemZaUsitHC4=,iv:tKnLw7iINiZCHfSinrAyqly+l/O4455ZWpFpUklA4w0=,tag:2jCSL6S2hjca52N+0StU3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QnFUYVhtamFyczhpMHRj
            UXpJSWxmZ09XcGhESHkzMDNMeGxCU01ONUNBCk5wZCtxQkN1TmxJMGFqMWhPQnRh
            aVAxc0RVS3FRWnlneHJVcitLOTdrOXcKLS0tIGpIK0trMmEwcURBMDNoWU5sejZW
            d05uYTNoM2ZYbHJwU0xqaHp4NEpkVmcKF87bgTORE6DNmN2FqWD81aKwP/ccmgaV
            hu1OiYcRh7qgds18iMxidXTRaGihavtgCmJWIXTzh+LIXMPdYTKJcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-07T21:38:53Z"
    mac: ENC[AES256_GCM,data:SdlOr8Kb7FVmsvtYsz+gvBkcczdK7D1qZ6b3hZ8EUWUJKDFGX+FJQfpZwuxu/0BXkPKubqobUNmIXaK4nVDPg351ML3llKhG743MZeZoZYoCzj0ckjlGZug59FmF4hMrB7FRjlqdKx4uN46di0/XcUWyRb2AZiHY0vmdwd+sLn4=,iv:+FkqTRkzaLL4BiaRig75uOdORiBEBrYVcd3O3H6JhJk=,tag:1k3pWaKvU8O0OBAw8TZsUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
