apiVersion: v1
kind: Secret
metadata:
    name: jenkins-secret
    namespace: jenkins
type: Opaque
stringData:
    JENKINS_USER: ENC[AES256_GCM,data:4rfdwFeT,iv:pQswdkOZx7ViG3xLW2RL+38RzvSOhaBLQaSSyAJcCFs=,tag:zZb1/0rrXYpMOkk8196iFw==,type:str]
    JENKINS_PASSWD: ENC[AES256_GCM,data:kEIEITjoN45miLQ=,iv:/F2AtGkTVdIpVBtG0kf8lga0A1BKaW4pemNyC+TEWCw=,tag:GtJeJQDcEB5BXVdF5QrLxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QnFUYVhtamFyczhpMHRj
            UXpJSWxmZ09XcGhESHkzMDNMeGxCU01ONUNBCk5wZCtxQkN1TmxJMGFqMWhPQnRh
            aVAxc0RVS3FRWnlneHJVcitLOTdrOXcKLS0tIGpIK0trMmEwcURBMDNoWU5sejZW
            d05uYTNoM2ZYbHJwU0xqaHp4NEpkVmcKF87bgTORE6DNmN2FqWD81aKwP/ccmgaV
            hu1OiYcRh7qgds18iMxidXTRaGihavtgCmJWIXTzh+LIXMPdYTKJcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-07T13:10:24Z"
    mac: ENC[AES256_GCM,data:qMPwjh4YUXdXo1qr6NbVCuwbuyrpoOHrkhCs32ho4SEOB5Uja3Wo8OUOKp6bx3Q516wq/GiM697Nbj1J53KNmnPT6+1re7jB4Av/98B4hN4WqFwFfTSC//5vveQ5NztfAuGlgkfrFdx0m4YWgATm5zHlJ+5FvhlbzrGjUoR2fAQ=,iv:7ZMlChjMhlt5R7ICW0kJ5rjyzKOs9NDUoovTqWSK53Y=,tag:U0z8SDcZ8b7T33MFojtfJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
