apiVersion: v1
kind: Secret
metadata:
    name: jenkins
    namespace: jenkins
    label:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: jenkins
        meta.helm.sh/release-namespace: jenkins
type: Opaque
stringData:
    jenkinsUser: ENC[AES256_GCM,data:yVXFt1/k,iv:P/eoe3A6e2+NjAOsljoYDj8RDO+sZJKoRbPm9SL8e6A=,tag:yEZG1qvN3lifAe/BM3f7RQ==,type:str]
    jenkinsPassword: ENC[AES256_GCM,data:gmCxSeIfB0zaTaY=,iv:Nj1YGCwR8nz7wtcck+w0TegynyULQBe9mak7TPXDwnY=,tag:wFNgZztuKdm+8sFNQMFO6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QnFUYVhtamFyczhpMHRj
            UXpJSWxmZ09XcGhESHkzMDNMeGxCU01ONUNBCk5wZCtxQkN1TmxJMGFqMWhPQnRh
            aVAxc0RVS3FRWnlneHJVcitLOTdrOXcKLS0tIGpIK0trMmEwcURBMDNoWU5sejZW
            d05uYTNoM2ZYbHJwU0xqaHp4NEpkVmcKF87bgTORE6DNmN2FqWD81aKwP/ccmgaV
            hu1OiYcRh7qgds18iMxidXTRaGihavtgCmJWIXTzh+LIXMPdYTKJcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-07T21:41:58Z"
    mac: ENC[AES256_GCM,data:8kTo0/l7sURd7bX9w/4EBpBa1s7JrhN3x54rDvIrqlaOhTU5D13KZOhand7oeEpdsgYZqgwMcIGhjq66HksvCL2ug4ta+6OU/y374wyjK5G2i74rs01Rb5jw9Snfxk6vVASt7VESOBNTFcyw4klcWPuMo1brVKaAAkmUVTMA69A=,iv:nZyPSXCvArMhGntfGjVTfHw6pz91/ueLJUii/AjcWxA=,tag:2LBPtSV+XDY8jC18NgE3Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
