# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:yMrD+m3e/DggfSASbNgQaT5vK3dTX1mC7NdPOtpcEj0bt+yh/Q==,iv:o3aYMrv1m48yy0/9yezpFhZ5TlHH3tX2lTxs6SpeV1g=,tag:H3nGhviKPMggyxibMKvC5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3asqdrew0uw4cmqhzrl2n2x2rekw4y0caqd3z9susnpxsvxy3cqfcckew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU2hIRmhDTlJjb0g1NEt2
            R0JGVVlqc1NhODlKZ0loSklkT2JWZExIeDFJCms4blpkVDBDaUNLS0prWVN4NmlN
            SzZOYnhOelYvdytkNFNCUEVsM1E4eG8KLS0tIHB0NTlubEhQRnJBY2o5blVSUXJk
            dk1DRHRxbW9KK0N1bnM0akhDc1pGVDQKQSs8/ONeqEA1xsTyTMCUQSMOUDwPF7Nx
            nsnpkGG58R7fnTt5v+1R+RBvNl2RW/yOnkpF5Vpjh0CAj0H3MM0/Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-25T03:39:09Z"
    mac: ENC[AES256_GCM,data:hUnhCKJh7KckN91a7DUVfhQZnE4SHeJJ9tJQX8qRnSuRFE43MQGxi6ccEWc53JEQ9r8o0KbEzbsPVZ/OB8WiLvEhSOpzF3VOmZnIVkWrgd98wm1tcuFcn0VC6R1tYD7Of/AuUH08GJLYmnLUnVw4nyMHYBLIDZrq8lh2RAgbMD8=,iv:DBFkm4mcg4cmm7iRoFWnB0LwM7v4gppSEppNdw20xpQ=,tag:jaGtk3lru7osY1hgM9n7dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
