---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  values:
    communications:
      discord:
        enabled: true
        token: "${BOTKUBE_TOKEN}"
        botid: ${BOTKUBE_BOTID}
        channel: ${BOTKUBE_CHANNEL}
    serviceMonitor:
      enabled: false
    config:
      recommendations: false
      settings:
        clustername: monado
      resources:
      - name: v1/pods
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: v1/services
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: apps/v1/deployments
        namespaces:
          include:
          - all
        events:
        - create
        - update
        - delete
        - error
      - name: apps/v1/statefulsets
        namespaces:
          include:
          - all
        events:
        - create
        - update
        - delete
        - error
      - name: networking.k8s.io/v1beta1/ingresses
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: v1/nodes
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: v1/namespaces
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: v1/persistentvolumes
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: v1/persistentvolumeclaims
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: v1/configmaps
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: apps/v1/daemonsets
        namespaces:
          include:
          - all
        events:
        - create
        - delete
        - error
      - name: batch/v1/jobs
        namespaces:
          include:
          - all
        events:
        - update
        - error
