---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system.yaml
  - kube-system.yaml
  - cert-manager.yaml
  - metallb-system.yaml
  - networking.yaml
  - media.yaml
  - monitoring.yaml
  - calico-system.yaml
  - rook-ceph.yaml
